<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'Scheduled_Appointments_id',
'Scheduled_Appointments_title',
'Scheduled_Appointments_start',
'Scheduled_Appointments_end',
'Scheduled_Appointments_accountID',
'Scheduled_Appointments_date_created',
'Scheduled_Appointments_date_modified',
'Scheduled_Appointments_last_modified_by',
'Scheduled_Appointments_status',
'Scheduled_Appointments_doctor_id',
'Scheduled_Appointments_email',
'Scheduled_Appointments_serviceID' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'Scheduled_Appointments_id' => array( 'integrated_search_field' ),
'Scheduled_Appointments_title' => array( 'integrated_search_field1' ),
'Scheduled_Appointments_start' => array( 'integrated_search_field2' ),
'Scheduled_Appointments_end' => array( 'integrated_search_field3' ),
'Scheduled_Appointments_accountID' => array( 'integrated_search_field4' ),
'Scheduled_Appointments_date_created' => array( 'integrated_search_field5' ),
'Scheduled_Appointments_date_modified' => array( 'integrated_search_field6' ),
'Scheduled_Appointments_last_modified_by' => array( 'integrated_search_field7' ),
'Scheduled_Appointments_status' => array( 'integrated_search_field8' ),
'Scheduled_Appointments_doctor_id' => array( 'integrated_search_field9' ),
'Scheduled_Appointments_email' => array( 'integrated_search_field10' ),
'Scheduled_Appointments_serviceID' => array( 'integrated_search_field11' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'search_header' ),
'above-grid' => array(  ),
'below-grid' => array( 'search_search',
'search_reset',
'search_back_list',
'search_cancel' ),
'grid' => array( 'integrated_search_field',
'integrated_search_field1',
'integrated_search_field2',
'integrated_search_field3',
'integrated_search_field4',
'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field8',
'integrated_search_field9',
'integrated_search_field10',
'integrated_search_field11' ) ),
'formXtTags' => array( 'above-grid' => array(  ) ),
'itemForms' => array( 'search_header' => 'top',
'search_search' => 'below-grid',
'search_reset' => 'below-grid',
'search_back_list' => 'below-grid',
'search_cancel' => 'below-grid',
'integrated_search_field' => 'grid',
'integrated_search_field1' => 'grid',
'integrated_search_field2' => 'grid',
'integrated_search_field3' => 'grid',
'integrated_search_field4' => 'grid',
'integrated_search_field5' => 'grid',
'integrated_search_field6' => 'grid',
'integrated_search_field7' => 'grid',
'integrated_search_field8' => 'grid',
'integrated_search_field9' => 'grid',
'integrated_search_field10' => 'grid',
'integrated_search_field11' => 'grid' ),
'itemLocations' => array( 'integrated_search_field' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field1' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field2' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field3' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field4' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field5' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field6' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field7' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field8' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field9' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field10' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field11' => array( 'location' => 'grid',
'cellId' => 'c1' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'search_header' => array( 'search_header' ),
'search_reset' => array( 'search_reset' ),
'search_back_list' => array( 'search_back_list' ),
'search_search' => array( 'search_search' ),
'search_cancel' => array( 'search_cancel' ),
'integrated_search_field' => array( 'integrated_search_field',
'integrated_search_field1',
'integrated_search_field2',
'integrated_search_field3',
'integrated_search_field4',
'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field8',
'integrated_search_field9',
'integrated_search_field10',
'integrated_search_field11' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field',
'integrated_search_field1',
'integrated_search_field2',
'integrated_search_field3',
'integrated_search_field4',
'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field8',
'integrated_search_field9',
'integrated_search_field10',
'integrated_search_field11' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'search',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'search',
'type' => 'search',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'search-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'search_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'search-above-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'search-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'search_search',
'search_reset',
'search_back_list',
'search_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-search',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_search_field',
'integrated_search_field1',
'integrated_search_field2',
'integrated_search_field3',
'integrated_search_field4',
'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field8',
'integrated_search_field9',
'integrated_search_field10',
'integrated_search_field11' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'separateLabels' => false ) ),
'items' => array( 'search_header' => array( 'type' => 'search_header' ),
'search_reset' => array( 'type' => 'search_reset' ),
'search_back_list' => array( 'type' => 'search_back_list' ),
'search_search' => array( 'type' => 'search_search' ),
'search_cancel' => array( 'type' => 'search_cancel' ),
'integrated_search_field' => array( 'field' => 'Scheduled_Appointments_id',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field1' => array( 'field' => 'Scheduled_Appointments_title',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field2' => array( 'field' => 'Scheduled_Appointments_start',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field3' => array( 'field' => 'Scheduled_Appointments_end',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field4' => array( 'field' => 'Scheduled_Appointments_accountID',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field5' => array( 'field' => 'Scheduled_Appointments_date_created',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field6' => array( 'field' => 'Scheduled_Appointments_date_modified',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field7' => array( 'field' => 'Scheduled_Appointments_last_modified_by',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field8' => array( 'field' => 'Scheduled_Appointments_status',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field9' => array( 'field' => 'Scheduled_Appointments_doctor_id',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field10' => array( 'field' => 'Scheduled_Appointments_email',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field11' => array( 'field' => 'Scheduled_Appointments_serviceID',
'type' => 'integrated_search_field',
'orientation' => 0 ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>