<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'doctor_id',
'first_name',
'last_name',
'middle_initial',
'title',
'gender',
'email',
'specialization',
'schedule_days',
'schedule_time_start',
'schedule_time_end' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'doctor_id' => array( 'import_field' ),
'first_name' => array( 'import_field1' ),
'last_name' => array( 'import_field2' ),
'middle_initial' => array( 'import_field3' ),
'title' => array( 'import_field5' ),
'gender' => array( 'import_field6' ),
'email' => array( 'import_field7' ),
'specialization' => array( 'import_field8' ),
'schedule_days' => array( 'import_field9' ),
'schedule_time_start' => array( 'import_field10' ),
'schedule_time_end' => array( 'import_field11' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'doctor_id',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'first_name',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'last_name',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'middle_initial',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'title',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'gender',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'email',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'specialization',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'schedule_days',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'schedule_time_start',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'schedule_time_end',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>