<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'id',
'title',
'start',
'end',
'status',
'doctor_id',
'email',
'serviceID',
'accountID1',
'first_name',
'last_name',
'middle_name',
'contact_no',
'address_line',
'barangay',
'city_province_region',
'email1',
'prefered_mode_of_payment',
'date_modified1',
'date_created1',
'last_modified_by1',
'full_name' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'id' => array( 'import_field' ),
'title' => array( 'import_field1' ),
'start' => array( 'import_field2' ),
'end' => array( 'import_field3' ),
'status' => array( 'import_field8' ),
'doctor_id' => array( 'import_field9' ),
'email' => array( 'import_field10' ),
'serviceID' => array( 'import_field11' ),
'accountID1' => array( 'import_field5' ),
'first_name' => array( 'import_field6' ),
'last_name' => array( 'import_field7' ),
'middle_name' => array( 'import_field12' ),
'contact_no' => array( 'import_field13' ),
'address_line' => array( 'import_field14' ),
'barangay' => array( 'import_field15' ),
'city_province_region' => array( 'import_field16' ),
'email1' => array( 'import_field17' ),
'prefered_mode_of_payment' => array( 'import_field18' ),
'date_modified1' => array( 'import_field19' ),
'date_created1' => array( 'import_field20' ),
'last_modified_by1' => array( 'import_field21' ),
'full_name' => array( 'import_field22' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field1',
'import_field2',
'import_field3',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field',
'import_field5',
'import_field6',
'import_field7',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid',
'import_field17' => 'grid',
'import_field18' => 'grid',
'import_field19' => 'grid',
'import_field20' => 'grid',
'import_field21' => 'grid',
'import_field22' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field5',
'import_field6',
'import_field7',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field1',
'import_field2',
'import_field3',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field',
'import_field5',
'import_field6',
'import_field7',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'id',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'title',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'start',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'end',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'status',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'doctor_id',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'email',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'serviceID',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'accountID1',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'first_name',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'last_name',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'middle_name',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'contact_no',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'address_line',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'barangay',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'city_province_region',
'type' => 'import_field' ),
'import_field17' => array( 'field' => 'email1',
'type' => 'import_field' ),
'import_field18' => array( 'field' => 'prefered_mode_of_payment',
'type' => 'import_field' ),
'import_field19' => array( 'field' => 'date_modified1',
'type' => 'import_field' ),
'import_field20' => array( 'field' => 'date_created1',
'type' => 'import_field' ),
'import_field21' => array( 'field' => 'last_modified_by1',
'type' => 'import_field' ),
'import_field22' => array( 'field' => 'full_name',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>