<?php
			$optionsArray = array( 'totals' => array( 'order_id' => array( 'totalsType' => '' ),
'account_id' => array( 'totalsType' => '' ),
'product_id' => array( 'totalsType' => '' ),
'quantity' => array( 'totalsType' => '' ),
'total' => array( 'totalsType' => '' ),
'date_of_purchase' => array( 'totalsType' => '' ),
'accountID' => array( 'totalsType' => '' ),
'first_name' => array( 'totalsType' => '' ),
'last_name' => array( 'totalsType' => '' ),
'email' => array( 'totalsType' => '' ),
'product_id1' => array( 'totalsType' => '' ),
'product_name' => array( 'totalsType' => '' ),
'price' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'order_id',
'account_id',
'product_id',
'quantity',
'total',
'date_of_purchase',
'accountID',
'first_name',
'last_name',
'email',
'product_id1',
'product_name',
'price' ),
'exportFields' => array( 'order_id',
'account_id',
'product_id',
'quantity',
'total',
'date_of_purchase',
'accountID',
'first_name',
'last_name',
'email',
'product_id1',
'product_name',
'price' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'order_id' => array( 'export_field' ),
'account_id' => array( 'export_field1' ),
'product_id' => array( 'export_field2' ),
'quantity' => array( 'export_field3' ),
'total' => array( 'export_field4' ),
'date_of_purchase' => array( 'export_field5' ),
'accountID' => array( 'export_field6' ),
'first_name' => array( 'export_field7' ),
'last_name' => array( 'export_field8' ),
'email' => array( 'export_field9' ),
'product_id1' => array( 'export_field10' ),
'product_name' => array( 'export_field11' ),
'price' => array( 'export_field12' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'order_id',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'account_id',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'product_id',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'quantity',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'total',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'date_of_purchase',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'accountID',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'first_name',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'last_name',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'email',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'product_id1',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'product_name',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'price',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 4,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>