<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'order_id',
'account_id',
'product_id',
'quantity',
'total',
'date_of_purchase',
'accountID',
'first_name',
'last_name',
'email',
'product_id1',
'product_name',
'price' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'order_id' => array( 'import_field' ),
'account_id' => array( 'import_field1' ),
'product_id' => array( 'import_field2' ),
'quantity' => array( 'import_field3' ),
'total' => array( 'import_field4' ),
'date_of_purchase' => array( 'import_field5' ),
'accountID' => array( 'import_field6' ),
'first_name' => array( 'import_field7' ),
'last_name' => array( 'import_field8' ),
'email' => array( 'import_field9' ),
'product_id1' => array( 'import_field10' ),
'product_name' => array( 'import_field11' ),
'price' => array( 'import_field12' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'order_id',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'account_id',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'product_id',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'quantity',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'total',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'date_of_purchase',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'accountID',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'first_name',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'last_name',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'email',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'product_id1',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'product_name',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'price',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>