<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */
 
 class eventclass_appointments  extends eventsBase
{
	function __construct()
	{
	// fill list of events

		$this->events["BeforeAdd"]=true;


		$this->events["AfterEdit"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record added
function BeforeAdd(&$values, &$message, $inline, &$pageObject)
{

				$title = $values['title'];
		$start = $values['start'];
		$end = $values['end'];
		$accountID = $values['accountID'];
		$status = $values['status'];
		$doctor_id = $values['doctor_id'];
		$email = $values['email'];
		$serviceID = $values['serviceID'];
		if ($values["serviceID"])
			{
			$arr = explode(",",$values["serviceID"]);
			// This is the name of the multi check box or
			// list select field, its value becomes $arr
			for ($i=0;$i<count($arr);$i++)
			{
			$strInsert = "insert into appointments (title,start,end,accountID,status,doctor_id,email,serviceID)";
			$strInsert.="Values('".$title."', '".$start."','".$end."',".$accountID.",'".$status."',".$doctor_id.",'".$email."',".$arr[$i].")";
		// add more fields from the add page to be inserted into database
			 
			  db_exec($strInsert);
			}
		}
?>
<script>
    window.parent.location.reload();
    window.parent.popup.close();
</script>
<?php
return false;
;		
} // function BeforeAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record updated
function AfterEdit(&$values, $where, &$oldvalues, &$keys, $inline, &$pageObject)
{

		
// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
