<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */
 
 class eventclass_doctors  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["AfterAdd"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, &$pageObject)
{

		

// Place event code here.
// Use "Add Action" button to add code snippets.
$data["username"] = $values["email"];
$data["password"] = md5("p@ssword1");
$data["fname"] = $values["first_name"];
$data["lname"] = $values["last_name"];
$data["status"] = 1;
$data["date_created"] = now();
$data["date_updated"] = now();
$data["access_type"] = "Doctor Account";
$data["last_modified_by"] = $_SESSION["UserName"];
$data["email"] = $values["email"];
DB::Insert("users", $data );

;		
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
