<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */
 
 class eventclass_new_walkin  extends eventsBase
{
	function __construct()
	{
	// fill list of events

		$this->events["BeforeAdd"]=true;


		$this->events["AfterEdit"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record added
function BeforeAdd(&$values, &$message, $inline, &$pageObject)
{

			$data = array();
$data["first_name"] = $values['first_name'];
$data["last_name"]= $values['last_name'];
$data['middle_name'] = $values['middle_name'];
$data['contact_no'] = $values['contact_no'];
$data['address_line'] = $values['address_line'];
$data['barangay'] = $values['barangay'];
$data['city_province_region'] = $values['city_province_region'];
$data['email'] = $values['email'];
$data['prefered_mode_of_payment'] = $values['prefered_mode_of_payment'];
$data['date_modified'] = now();
$data['date_created'] = now();
$data['last_modified_by'] = $_SESSION['UserName'];
DB::Insert("accounts", $data );

$accountID = DB::LastId();	

		$title = $values['title'];
		$start = $values['start'];
		$end = $values['end'];
		$status = $values['status'];
		$doctor_id = $values['doctor_id'];
		$email = $values['email'];
		$serviceID = $values['serviceID'];
		if ($values["serviceID"])
			{
			$arr = explode(",",$values["serviceID"]);
			// This is the name of the multi check box or
			// list select field, its value becomes $arr
			for ($i=0;$i<count($arr);$i++)
			{
			$strInsert = "insert into appointments (title,start,end,accountID,status,doctor_id,email,serviceID)";
			$strInsert.="Values('".$title."', '".$start."','".$end."',".$accountID.",'".$status."',".$doctor_id.",'".$email."',".$arr[$i].")";
		// add more fields from the add page to be inserted into database
			 
			  db_exec($strInsert);
			}
		}

header("Location: administrator_dashboard.php");
exit();


return false;
;		
} // function BeforeAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record updated
function AfterEdit(&$values, $where, &$oldvalues, &$keys, $inline, &$pageObject)
{

		
// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
