<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */
 
 class eventclass_new_customer  extends eventsBase
{
	function __construct()
	{
	// fill list of events

	}

//	handlers


// dashboatd snippets function
function event_New_Customer_snippet( &$header )
{
	include "fullcalendar/index.php";;
}

}
?>
